title: "ReactとXRPL/XUMMで構築するWebアプリケーション"
summary: "ReactとXRPL/XUMMを使い、短期間でNFTをあつかうWebアプリケーションを構築する方法をご紹介します。"
topics: ["React", "Vite", "XRPL", "XUMM", "Vercel"] # トピック（5つまで）
published: true
price: 0 # 有料の場合200〜5000
chapters:
  - preface # チャプター1
  - installation # チャプター2
  - wallet # チャプター3
  - xprl-function # チャプター4
